spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: @project.artifactId@
    version: @project.version@

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG


